#!/bin/bash

DIST=$1

if [ -z "$DIST" ]; then
	echo "Usage: `basename $0` [DIST]"
	echo "  Current supported distributions: el6 el7"
	exit 1
fi

if [ "$DIST" != 'el6' ] && [ "$DIST" != 'el7' ]; then
	echo "Currently only el6 and el7 are supported."
	exit 1
fi

FWTREE_PATH='/usr/src/fwtree-git/'
TAR_PATH="/$FWTREE_PATH/tmp/"

mkdir $TAR_PATH
cp -a $FWTREE_PATH/rootfs/* $TAR_PATH/

if [ -d "$FWTREE_PATH/rootfs-$DIST" ]; then
	cp -a $FWTREE_PATH/rootfs-$DIST/* $TAR_PATH/
fi

SUBRELEASE=".$DIST"
VERSION=$(cat /$FWTREE_PATH/.version)
$FWTREE_PATH/buildscripts/mkrelease
PKGRELEASE=$(cat $FWTREE_PATH/.release)$SUBRELEASE
ARCH='noarch'
TARBALL="fwtree-$VERSION-${PKGRELEASE}.${ARCH}.tar"

export VERSION PKGRELEASE DIST ARCH SCRIPTS TARBALL

$FWTREE_PATH/buildscripts/mkspec > $FWTREE_PATH/fwtree.spec

tar -C $TAR_PATH -cf $TARBALL ./
rm -rf $TAR_PATH

rpmbuild -bb $FWTREE_PATH/fwtree.spec
rm -f $FWTREE_PATH/$TARBALL

RPMDIR='/root/rpmbuild/RPMS/noarch'
# Need to transfer RPM to deb8-dev to create .deb packages
RPM=$(ls -ltr $RPMDIR/fwtree-*.${DIST}.noarch.rpm |tail -n1 |awk '{print $9}')

if [ -n "$RPM" ]; then
	echo "Pushing $(basename $RPM) to deb8-dev and building deb packages."
	scp $RPM deb8-dev.ewi:/usr/src/fwtree-git/
	ssh deb8-dev.ewi "cd /usr/src/fwtree-git && ./build $(basename $RPM)"
fi

exit 0
