#!/bin/bash
# This script migrates the older /etc/iptables.d format into the new /etc/fwtree.d format.

set -e

OLD='/etc/iptables.d'
NEW='/etc/fwtree.d'

cd $OLD

echo "Converting $OLD to $NEW"

mkdir -p $NEW

find -type d -exec mkdir -p $NEW/{} \;
find * -type f -! -name '_*' -exec cp -a {} $NEW/{}.rule \;
rm $NEW/COMMENT.rule

find -type l | while read a; do
	LINK=$(readlink "$a")
	ln -s "${LINK}.rule" "$NEW/${a}.rule"
done

find -type d -name '_*' -exec mv $NEW/{} $NEW/{}.old \;
find -type d -name '_*' -exec ln -s /usr/share/fwtree/rules/{} $NEW/{} \;

ln -s /usr/share/fwtree/rules/COMMENT $NEW/COMMENT
find -type f -name '_BEGIN' -exec ln -s /usr/share/fwtree/rules/{} $NEW/{} \;
find -type f -name '_GLOBAL' -exec ln -s /usr/share/fwtree/rules/{} $NEW/{} \;

echo -n "Checking for broken symlinks... "
BROKEN=$(find $NEW/ -type l -! -exec test -e {} \; -print)

if [ "$BROKEN" ]; then
	NUM=$(echo "$BROKEN" |wc -l)
	echo "Found $NUM broken symlinks:"
	echo "$BROKEN" |xargs ls -l
else
	echo "None found."
fi


echo
echo "Once you have tested that everything is working, remember to rename or delete the following:"
echo
echo "  $OLD"
echo "  $NEW/*/_GLOBAL.old"

for i in /usr/local/bin/{fwtree,fwtree-parser,fw-update-blacklists,ipset-helper}; do
	if [ -x "$i" ]; then
		echo "  $i"
		chmod -x $i
	fi
done
echo
