#!/bin/bash
# Start fwtree
#
# chkconfig: - 09 92
# description:  Starts, stops and saves fwtree firewall
#
# config: /etc/fwtree.d/
# config: /etc/ipset.d/
#
### BEGIN INIT INFO
# Provides: fwtree
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: start and stop fwtree firewall
# Description: Start, stop and save fwtree firewall
### END INIT INFO


# Copyright (C) 2017 eWheeler, Inc. <copyright@o.ewheeler.net>
#
# This file is part of fwtree.
# 
# fwtree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# fwtree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with fwtree.  If not, see <http://www.gnu.org/licenses/>.

start() {
	ipset-helper -c
	fwtree | iptables-restore
}

stop() {
	iptables-restore < /usr/share/fwtree/fwtree-stop.ruleset
}

usage() {
	if [ -z "$1" ]; then
		echo "Usage: $0 (start|stop|reload|restart)"
		exit 0
	fi
}

LOCK=/var/lock/subsys/fwtree

case "$1" in
	start)
		start
		touch $LOCK &> /dev/null
	;;
	reload)
		start
	;;
	restart)
		stop ; start
	;;
	stop)
		stop
		rm $LOCK &> /dev/null
	;;
	*)
		usage
	;;
esac

exit 0
