#!/bin/bash
# Start fwtree
#
# chkconfig: 2345 09 92
# description:  Starts, stops and saves fwtree firewall
#
# config: /etc/fwtree.d/
# config: /etc/ipset.d/
#
### BEGIN INIT INFO
# Provides: fwtree
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop fwtree firewall
# Description: Start, stop and save fwtree firewall
### END INIT INFO

start() {
	ipset-helper -c
	fwtree | iptables-restore
}

stop() {
	iptables-restore < /usr/share/fwtree/fwtree-stop.ruleset
}

if [ -z "$1" ]; then
	echo "Usage: $0 (start|stop|reload|restart)"
	exit 0
fi

LOCK=/var/lock/subsys/fwtree

case "$1" in
	start)
		start
		touch $LOCK
	;;
	reload)
		start
	;;
	restart)
		stop ; start
	stop)
		stop
		rm $LOCK
	;;
	*)
		echo 1>&2 "Unsupported option $1"
		exit 1
	;;
esac

exit 0
