#!/bin/bash
# Copyright (C) 2017 eWheeler, Inc. <copyright@o.ewheeler.net>
#
# This file is part of fwtree.
# 
# fwtree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# fwtree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with fwtree.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -d '/etc/apt' ]; then
	exit 0
fi

cat /etc/apt/sources.list /etc/apt/sources.list.d/* 2> /dev/null |grep -v \# |cut -f3 -d / |grep . |sort -u
