#!/bin/bash
# Copyright (C) 2017 eWheeler, Inc. <copyright@o.ewheeler.net>
#
# This file is part of fwtree.
# 
# fwtree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# fwtree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with fwtree.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -x '/usr/bin/yum' ]; then
	exit 1
fi

CACHE=/var/tmp/ipset-yum-whitelist.cache

if [ -f $CACHE ] && ! [ -O $CACHE ]; then
	rm $CACHE
	mv $(mktemp) $CACHE || exit 1
fi

releasever=$(python -c 'import yum; yb = yum.YumBase(); print(yb.conf.yumvar["releasever"])' |tail -n1)
basearch=$(uname -m)

MIRRORS=$(grep -h ^mirrorlist /etc/yum.repos.d/*.repo |sed 's/mirrorlist=//' |sed "s/\$releasever/$releasever/g" |sed "s/\$basearch/$basearch/g")
BASEURLS=$(grep -h "^baseurl *= *http" /etc/yum.repos.d/*.repo |sed 's/baseurl=//')

echo -e "$MIRRORS\n$BASEURLS" |cut -d / -f3 |cut -f2 -d @ |sort -u

if ! [ -s $CACHE ] || [ "$(stat -c %Y $CACHE)" -lt "$(($(date +%s) - 3600))" ]; then
	for i in $MIRRORS; do
		wget -q -O - "$i" |egrep "https?://" |cut -d / -f3 |grep .
	done |sort -u > $CACHE
fi

cat "$CACHE"
