#!/bin/bash
# Copyright (C) 2017 eWheeler, Inc. <copyright@o.ewheeler.net>
#
# This file is part of fwtree.
# 
# fwtree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# fwtree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with fwtree.  If not, see <http://www.gnu.org/licenses/>.

cat /etc/fwtree.d/COMMENT

for TABLE in /etc/fwtree.d/* ; do
	if [ -d $TABLE ] ; then
		TABLE=`basename $TABLE`
		echo
		cat /etc/fwtree.d/$TABLE/_BEGIN
		for CHAIN in /etc/fwtree.d/$TABLE/* ; do
			if [ -d $CHAIN ] ; then
				CHAIN=`basename $CHAIN`
				# Skip special chains that start with underscore (such as _GLOBAL)
				if [ ${CHAIN:0:1} = '_' ] ; then 
					continue
				fi
				if ! grep -q "^:$CHAIN " /etc/fwtree.d/$TABLE/_BEGIN ; then
					echo ":$CHAIN - [0:0]"
				fi
			fi
		done
		echo
		RULE_COUNTER=0
		for CHAIN in /etc/fwtree.d/$TABLE/* ; do
			CHAIN=`basename $CHAIN`
			# Skip special chains that start with underscore (such as _GLOBAL)
			if [ ${CHAIN:0:1} = '_' ] ; then 
				continue
			fi
			echo
			echo "#####################################################################################"
			printf '#%84s\n' "$TABLE.$CHAIN"
			echo
			for RULE in /etc/fwtree.d/$TABLE/$CHAIN/*.rule ; do
				#BASERULE=$TABLE/$CHAIN/`basename $RULE`
				RULE_COUNTER=$(( $RULE_COUNTER + 1 ))
				if [ -f $RULE ] ; then
					export RULE
					export CHAIN
					export RULE_COUNTER
					fwtree-parser < "$RULE"
					echo
				fi
			done
			echo
			echo
		done
		echo COMMIT
	fi
done

