#!/usr/bin/perl -ln
# Copyright (C) 2017 eWheeler, Inc. <copyright@o.ewheeler.net>
#
# This file is part of fwtree.
# 
# fwtree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# fwtree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with fwtree.  If not, see <http://www.gnu.org/licenses/>.

my $line = $_;
chomp $line;

my $var;
my $exec;
if ($line =~ /(\w+)=`([^`]+)`/) {
	$var = $1;
	$exec = `$2`;
}

#$line =~ s/(\w+)=`([^`]+)`/$exec{$1}/g

if ($line =~ /^\s*[^#]/) {
	if (defined $exec) {
		for my $replacement (split /\s+/s, $exec) {
			my $l = $line;
			$l =~ s/(\w+)=`([^`]+)`/$replacement/;
			$l =~ s/\$$var/$replacement/g;
			
			
			if ($l =~ /AUTOLOG=\((\w+),([^,]+)(?:,([^)]+))?\)/) {
				$auto_counter++;
				my $chain = "AUTOLOG_$ENV{RULE_COUNTER}_$auto_counter";
				print "\n:$chain - [0:0]";
				print "-A $chain -j LOG --log-prefix \"$replacement: \" --log-level 7 $3";
				print "-A $chain -j $1";
				$l =~ s/AUTOLOG=\([^)]+\)/$chain/;
			}
			
			print "-A $ENV{CHAIN} $l -m comment --comment \"$ENV{RULE}:$.\"";
		}
	}
	else {
		print "-A $ENV{CHAIN} $line -m comment --comment \"$ENV{RULE}:$.\"";
	}
}
else {
	print $line;
}

